all: cansat_viewer
	# Done
cansat_viewer: cansat_viewer.cpp
	g++ cansat_viewer.cpp -o cansat_viewer  -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_primitives -lallegro_font -lallegro_ttf
