all: wykres_ojdana
	# Done
wykres_ojdana: wykres_ojdana.cpp
	g++ wykres_ojdana.cpp -o wykres_ojdana  -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_primitives -lallegro_font -lallegro_ttf

